{{- if .Values.externalPostgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.postgresSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  host: {{ .Values.externalPostgres.host | required "externalPostgres.host is required" | quote }}
  port: {{ .Values.externalPostgres.port | quote }}
  database: {{ .Values.externalPostgres.dbName | required "externalPostgres.dbName is required" | quote }}
  username: {{ .Values.externalPostgres.username | required "externalPostgres.username is required" | quote }}
  password: {{ .Values.externalPostgres.password | required "externalPostgres.password is required (or use --set)" | quote }}
  sslmode: {{ .Values.externalPostgres.sslmode | default "prefer" | quote }}
  type: {{ .Values.externalPostgres.type | default "unmanaged" | quote }}
{{- end }}
